const CURRENT_WEATHER_REQUEST = "CURRENT_WEATHER_REQUEST";
const CURRENT_WEATHER_SUCCESS = "CURRENT_WEATHER_SUCCESS";
const CURRENT_WEATHER_FAILURE = "CURRENT_WEATHER_FAILURE";


export {CURRENT_WEATHER_REQUEST, CURRENT_WEATHER_FAILURE, CURRENT_WEATHER_SUCCESS}